// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderBook.Api.Persistence;

#nullable disable

namespace OrderBook.Api.Persistence.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OrderBook.Api.Persistence.OrderBookSnapshotAudit", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderBookJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SnapshotId");

                    b.ToTable("OrderBookSnapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
